INSERT INTO USERS
  (USER_NAME, USER_PASSWORD)
VALUES
  ('AnikaDom', 'nevertheless');

INSERT INTO PLACES (CITY_NAME)
VALUES
  ('LOS ANGELES'),
  ('NEW YORK'),
  ('PARIS');

INSERT INTO TRAVELERS (EMPLOYEE_NAME)
VALUES
  ('Maksym Novakh'),
  ('AbuYan NovaXam');
