INSERT INTO USERS
  (USER_NAME, USER_PASSWORD)
VALUES
  ('AnikaDom', 'nevertheless');

INSERT INTO PLACES (CITY)
VALUES
  ('LOS ANGELES'),
  ('NEW YORK'),
  ('PARIS');

INSERT INTO TRAVELERS (NAME)
VALUES ('MAKSYM NOVAKH');