CREATE TABLE USERS (
  ID serial,
  USER_NAME VARCHAR(100) NOT NULL,
  USER_PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE PLACES (
  ID serial PRIMARY KEY
  CITY VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TRAVELERS (
  ID serial PRIMARY KEY
  NAME VARCHAR(100) NOT NULL UNIQUE,
  POSITION VARCHAR(100),
  DEPARTMENT VARCHAR(100),
  PHONE VARCHAR(100),
  EMAIL VARCHAR(100)
);

CREATE TABLE TRIPS (
  ID serial,
  TRAVELER_ID INT references TRAVELERS(ID),
  DESTINATION_ID INT references PLACES(ID),
  BUDGET FLOAT(2),
  TIME DATE,
  GOAL VARCHAR(256)
);
